// Centralized exports for all Tabler icons used in the application
// This allows us to import all icons from a single location
export {
  IconInfoCircle,
  IconUserPlus,
  IconCircleCheck,
  IconTags,
  IconShoppingCart,
  IconX,
  IconFlag,
  IconFlag2,
  IconFlag3,
  IconFlagOff,
  IconPin,
  IconCircleDot,
  IconPencil,
  IconPaperclip,
  IconCheck,
  IconArrowDown,
  IconArrowRight,
  IconArrowUp,
  IconAlertCircle,
  IconPhone,
  IconMail,
  IconDeviceMobile,
  IconMoodSmile,
  IconNotes,
  IconInbox,
  IconUser,
  IconSettings,
  IconLogout,
  IconCircleCheckFilled,
  IconCircleDotted,
  IconFlagFilled,
  IconChevronDown,
  IconChevronRight,
  IconRotateClockwise,
  IconPlus,
  IconGripVertical,
  IconDots,
  IconMessage,
  IconLayoutKanban,
  IconList,
  IconRefresh,
  IconTrash,
  IconPhoto,
  IconSend,
  IconLink,
  IconSearch,
  IconFilter,
  IconAdjustments,
  IconCircle,
} from '@tabler/icons-react';

